### ISSUE TITLE
Load addons button is on, chat says it loaded, but nothing happens

### ISSUE THREAD

**Issue by vfedele** [Excrulon/Tree-of-Savior-Addons#156]
Hello.
I´ve downloaded , unzipped, moved it to the steam file and opened the game.
When I log in, I see the 'LOAD ADDONS' buntton in the centre of the screen, I click it and in the chat I receive the message "better quest; channel surfer; context menu loaded" ( and the same message pops up in red) but nothing happens.
What should I do to activate it properly?

**Comment by Excrulon** [comment]
I don't know.

**Comment by vfedele** [comment]
:o  ok... thx anyway

**Comment by TehSeph** [comment]
Open you addon folder and look for the next addon in alphabetical order after "contextmenuadditions" since that is the last correctly loaded addon. The addon after it isn't installed correctly.

More than likely, you downloaded the lua source code of an ipf addon and placed it in the addon folder, instead of downloading the compiled ipf and placing it in the data folder. Delete that folder and re-download the addon properly.

**Comment by Yapapalicious** [comment]
Seems to me like addonloader is missing

**Comment by Excrulon** [comment]
I only recommend installing from the [latest release](https://github.com/Excrulon/Tree-of-Savior-Lua-Mods/releases/latest). Things in the repo aren't guaranteed to be working yet and I'm not supporting them if people have issues. I know that a couple of the ipfs aren't fully working yet.
