### ISSUE TITLE
Channel Surfer (error/bug?)

### ISSUE THREAD

**Issue by Dainishi** [Excrulon/Tree-of-Savior-Addons#185]
I'm update channel surfer v1.0.0 to v1.0.1 , then i play.. then i want change channel.. but, when i click other channel (example: i click "Channel 5")nothing happen.

**Comment by Excrulon** [comment]
I only really support itos since imc has different versions of code across each version one and itos is what I play. You guys still have old code. Manually copy over v1.0.0 and see if that fixes it.

https://github.com/Excrulon/Tree-of-Savior-Addons/releases/download/brandish/channelsurfer-v1.0.0.ipf

And put a unicode character in the filename. ⛄
